
services:
  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
    restart: always
    environment:
      - NEXT_PUBLIC_HOST_ADDRESS=http://localhost:8080
    depends_on:
      - backend

  # Backend (Go)
  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - SESSION_KEY=thesecret
      - SESSION_SECRET=thesecret
      - HOST_ADDRESS=http://localhost:8080
      - HOST_DOMAIN=localhost
      - DATABASE_PASSWORD=laplas
      - DATABASE_USER=postgres
      - DATABASE_NAME=toimi
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgress
    depends_on:
      - postgress

  # Nginx reverse proxy
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend

  # PostgreSQL Database
  postgress:
    image: postgres:13
    restart: always
    ports:
      - "8089:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=laplas
      - POSTGRES_DB=toimi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql



